const test=require("node:test"), assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {JSDOM}=require("jsdom"),jquery=require("jquery");
function setup(options={}) {
  const dom=new JSDOM('<button id="origin">Upload</button><div id="host"></div>',{runScripts:"outside-only",url:"http://localhost"});
  for (const [key,value] of Object.entries(options.storage || {})) dom.window.localStorage.setItem(key,value);
  const $=jquery(dom.window), modules={jquery:$};
  dom.window.define=(name,deps,factory)=>modules[name]=factory(...deps.map(dep=>modules[dep]));
  for (const name of ["icons","column-preflight-ui"]) {
    const file=path.join(__dirname,"../../ujg-excel-story-importer-modules/"+name+".js");
    if (fs.existsSync(file)) dom.window.eval(fs.readFileSync(file,"utf8"));
  }
  assert.equal(typeof modules._ujgESI_columnPreflightUi?.create,"function");
  const calls={choice:[],cancel:0,confirm:0,sheet:[],header:[],remember:[]};
  const columns=[{index:0,header:"Текст",letter:"A",occurrence:0,examples:["<b>Remark</b>"],nonEmptyCount:11},
    {index:1,header:"Ответственный",letter:"B",occurrence:0,examples:["Анна"],nonEmptyCount:5},
    {index:2,header:"Ответственный",letter:"C",occurrence:1,examples:["Иван"],nonEmptyCount:7}];
  const state={preferencesStorageKey:options.user || "user1",pendingImport:{fileName:"test.xlsx",settings:{},remember:true,report:{sheetName:"Замечания",sheetNames:["Замечания","Другое"],headerRowNumber:3,
    columns,fields:[{key:"summary",label:"Название",required:true,selectedIndex:0,status:"matched"},
      {key:"owner",label:"Ответственный",required:false,selectedIndex:null,status:"ambiguous"}],
    counts:{total:70,visible:11,hidden:59},needsReview:true,canApply:false}}};
  const services={onImportColumnChoice:(...args)=>calls.choice.push(args),onCancelColumnImport:()=>calls.cancel++,onConfirmColumnImport:()=>calls.confirm++,
    onImportSheetChange:n=>calls.sheet.push(n),onImportHeaderChange:n=>calls.header.push(n),onImportRememberChange:v=>calls.remember.push(v)};
  const ui=modules._ujgESI_columnPreflightUi.create();dom.window.document.querySelector("#origin").focus();
  const render=()=>ui.render($("#host"),state,services);render();
  return {dom,$,ui,state,calls,render,close:()=>{ui.destroy();dom.window.close();}};
}
test("preflight shows mismatches, counts and examples as text",t=>{const x=setup();t.after(x.close);
  assert.equal(x.$('[role="dialog"]').length,1);assert.match(x.$("#host").text(),/59/);
  assert.match(x.$("#host").text(),/Несколько совпадений/);assert.equal(x.$("#host b").length,0);
  assert.equal(x.$("select").length,0);assert.equal(x.$('[data-preflight-confirm]').prop("disabled"),true);
});
test("search selects an exact duplicate column without applying the import",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-field="owner"]')[0].click();
  x.$('[data-preflight-search]').val("Ответственный").trigger("input");
  assert.equal(x.$('[data-preflight-option]:not([hidden])').length,2);
  x.$('[data-preflight-option="2"]')[0].click();assert.deepEqual(x.calls.choice,[["owner",2]]);assert.equal(x.calls.confirm,0);
});
test("duplicate options include occurrence and opening a picker closes the column menu",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-columns]')[0].click();
  x.$('[data-preflight-filter="field"]')[0].click();
  assert.equal(x.$('.ujg-esi-preflight-columns-menu').length,0);
  x.$('[data-preflight-field="owner"]')[0].click();
  assert.match(x.$('[data-preflight-option="1"]').attr('aria-label'),/1 из 2/);
  assert.match(x.$('[data-preflight-option="2"]').attr('aria-label'),/2 из 2/);
});
test("unresolved summary does not claim that there are zero remarks",t=>{const x=setup();t.after(x.close);
  x.state.pendingImport.report.fields[0].selectedIndex=null;x.render();
  assert.match(x.$('.ujg-esi-preflight-counts').text(),/не определено/);
});
test("skip is explicit and unavailable for required summary",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-field="summary"]')[0].click();assert.equal(x.$('[data-preflight-skip]').length,0);
  x.$('[data-preflight-field="owner"]')[0].click();x.$('[data-preflight-skip]')[0].click();
  assert.deepEqual(x.calls.choice,[["owner",null]]);
});
test("escape first dismisses picker then dialog, close restores focus and overflow",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-field="owner"]')[0].click();
  const escape=()=>x.dom.window.document.dispatchEvent(new x.dom.window.KeyboardEvent("keydown",{key:"Escape",bubbles:true}));
  escape();assert.equal(x.calls.cancel,0);assert.equal(x.$('[data-preflight-search]').length,0);
  escape();assert.equal(x.calls.cancel,1);x.state.pendingImport=null;x.render();
  assert.equal(x.dom.window.document.activeElement.id,"origin");assert.equal(x.dom.window.document.body.style.overflow,"");
});
test("sheet header remember and confirmation use dedicated callbacks",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-sheet]')[0].click();x.$('[data-preflight-sheet-option="Другое"]')[0].click();assert.deepEqual(x.calls.sheet,["Другое"]);
  x.$('[data-preflight-header]').val("5").trigger("change");assert.deepEqual(x.calls.header,[5]);
  x.$('[data-preflight-remember]').prop("checked",false).trigger("change");assert.deepEqual(x.calls.remember,[false]);
  x.state.pendingImport.report.canApply=true;x.render();x.$('[data-preflight-confirm]')[0].click();assert.equal(x.calls.confirm,1);
});
test("closing after toolbar redraw restores focus to the replacement upload input",t=>{const x=setup();t.after(x.close);
  x.$('#origin').remove();x.$('body').append('<input class="ujg-esi-file" type="file">');
  x.state.pendingImport=null;x.render();
  assert.equal(x.dom.window.document.activeElement,x.$('.ujg-esi-file')[0]);
});
test("header filter searches draft values, applies multiple selections, and resets independently of sort",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-filter="status"]')[0].click();
  x.$('[data-preflight-filter-search]').val("несколько").trigger("input");
  assert.equal(x.$('[data-preflight-filter-value]:not([hidden])').length,1);
  x.$('[data-preflight-filter-value="ambiguous"] input').prop("checked",false).trigger("change");
  x.$('[data-preflight-filter-search]').val("").trigger("input");
  x.$('[data-preflight-filter-value="matched"] input').prop("checked",false).trigger("change");
  assert.equal(x.$('[data-preflight-row]').length,2);
  x.$('[data-preflight-filter-apply]')[0].click();assert.equal(x.$('[data-preflight-row]').length,0);
  x.$('[data-preflight-sort="status"]')[0].click();
  x.$('[data-preflight-filter="status"]')[0].click();x.$('[data-preflight-filter-reset]')[0].click();
  assert.equal(x.$('[data-preflight-row]').length,2);
  assert.ok(x.$('[data-preflight-sort="status"]').text().includes("↑"));
  assert.equal(JSON.parse(x.dom.window.localStorage.getItem("user1:column-preflight-ui")).sort.id,"status");
});
test("Escape and outside click discard filter draft while mapping remains editable",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-filter="field"]')[0].click();
  x.$('[data-preflight-filter-value="Название"] input').prop("checked",false).trigger("change");
  x.dom.window.document.dispatchEvent(new x.dom.window.KeyboardEvent("keydown",{key:"Escape",bubbles:true}));
  assert.equal(x.$('[data-preflight-row]').length,2);assert.equal(x.calls.cancel,0);
  x.$('[data-preflight-filter="field"]')[0].click();
  x.dom.window.document.querySelector("#origin").dispatchEvent(new x.dom.window.MouseEvent("mousedown",{bubbles:true}));
  assert.equal(x.$('[data-preflight-filter-search]').length,0);
  assert.equal(x.$('[data-preflight-field]').length,2);
});
test("column visibility, reorder, and widths persist per user and view",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-columns]')[0].click();
  x.$('[data-preflight-visible="examples"]').prop("checked",false).trigger("change");
  assert.equal(x.$('th[data-column="examples"]').length,0);
  const dataTransfer={data:{},setData(type,value){this.data[type]=value;},getData(type){return this.data[type];}};
  x.$('th[data-column="status"]').trigger(x.$.Event("dragstart",{originalEvent:{dataTransfer}}));
  x.$('th[data-column="field"]').trigger(x.$.Event("drop",{originalEvent:{dataTransfer,preventDefault(){}}}));
  assert.equal(x.$('thead th').first().attr("data-column"),"status");
  x.$('th[data-column="status"] [data-preflight-resize]').trigger(x.$.Event("keydown",{key:"ArrowRight"}));
  const saved=x.dom.window.localStorage.getItem("user1:column-preflight-ui");
  assert.equal(JSON.parse(saved).widths.status,220);
  const y=setup({storage:{"user1:column-preflight-ui":saved}});t.after(y.close);
  assert.equal(y.$('thead th').first().attr("data-column"),"status");assert.equal(y.$('th[data-column="examples"]').length,0);
  const other=setup({user:"user2",storage:{"user1:column-preflight-ui":saved}});t.after(other.close);
  assert.equal(other.$('thead th').first().attr("data-column"),"field");assert.equal(other.$('th[data-column="examples"]').length,1);
});
test("column menu reopens after redraw, protects last visible column, and reset keeps filters",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-filter="status"]')[0].click();
  x.$('[data-preflight-filter-value="ambiguous"] input').prop("checked",false).trigger("change");
  x.$('[data-preflight-filter-apply]')[0].click();
  x.$('[data-preflight-columns]')[0].click();
  for(const id of ["column","examples","status"]) {
    x.$(`[data-preflight-visible="${id}"]`).prop("checked",false).trigger("change");
  }
  x.$('[data-preflight-visible="field"]').prop("checked",false).trigger("change");
  assert.equal(x.$('thead th').length,1);assert.equal(x.$('thead th').attr("data-column"),"field");
  x.$('.ujg-esi-preflight-columns-menu button').last()[0].click();
  assert.equal(x.$('thead th').length,4);assert.equal(x.$('[data-preflight-row]').length,1);
});
test("Escape closes column menu without cancelling import and canceled resize restores width",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-columns]')[0].click();
  x.dom.window.document.dispatchEvent(new x.dom.window.KeyboardEvent("keydown",{key:"Escape",bubbles:true}));
  assert.equal(x.calls.cancel,0);assert.equal(x.$('.ujg-esi-preflight-columns-menu').length,0);
  x.$('[data-preflight-resize="field"]').trigger(x.$.Event("pointerdown",{pageX:100}));
  x.$(x.dom.window.document).trigger(x.$.Event("pointermove",{pageX:155}));
  x.$(x.dom.window.document).trigger("pointercancel");
  assert.equal(x.$('th[data-column="field"]').css("width"),"220px");
});
test("visibility changes keep column menu open and keyboard focus on the checkbox",t=>{const x=setup();t.after(x.close);
  x.$('[data-preflight-columns]')[0].click();
  x.$('[data-preflight-visible="examples"]').prop("checked",false).trigger("change");
  assert.equal(x.$('.ujg-esi-preflight-columns-menu').length,1);
  assert.equal(x.dom.window.document.activeElement.getAttribute("data-preflight-visible"),"examples");
  x.$('[data-preflight-visible="status"]').prop("checked",false).trigger("change");
  assert.equal(x.$('thead th').length,2);
});
test("hidden active filter stays editable and redraw preserves scroll and resize focus",t=>{const x=setup();t.after(x.close);
  const scroll=x.$('.ujg-esi-preflight-scroll')[0];scroll.scrollTop=45;scroll.scrollLeft=30;
  x.$('[data-preflight-filter="status"]')[0].click();
  x.$('[data-preflight-filter-value="ambiguous"] input').prop("checked",false).trigger("change");
  x.$('[data-preflight-filter-apply]')[0].click();
  x.$('[data-preflight-columns]')[0].click();
  x.$('[data-preflight-visible="status"]').prop("checked",false).trigger("change");
  assert.equal(x.$('.ujg-esi-preflight-hidden-filter').length,1);
  x.$('.ujg-esi-preflight-hidden-filter')[0].click();
  assert.equal(x.$('[data-preflight-filter-value="ambiguous"] input').prop("checked"),false);
  x.dom.window.document.dispatchEvent(new x.dom.window.KeyboardEvent("keydown",{key:"Escape",bubbles:true}));
  const handle=x.$('[data-preflight-resize="field"]')[0];handle.focus();
  x.$(handle).trigger(x.$.Event("keydown",{key:"ArrowRight"}));
  assert.equal(x.dom.window.document.activeElement.getAttribute("data-preflight-resize"),"field");
  assert.equal(x.$('.ujg-esi-preflight-scroll')[0].scrollTop,45);
  assert.equal(x.$('.ujg-esi-preflight-scroll')[0].scrollLeft,30);
});
